// SPDX-FileCopyrightText: 2025 Antoni Szymański
// SPDX-License-Identifier: MPL-2.0

package invidious

import "time"

type ImageObject struct {
	Url    string `json:"url"`
	Width  int64  `json:"width"`
	Height int64  `json:"height"`
}

type ThumbnailObject struct {
	Quality string `json:"quality"`
	Url     string `json:"url"`
	Width   int64  `json:"width"`
	Height  int64  `json:"height"`
}

type VideoObject struct {
	Type            string            `json:"type"` // "video"
	Title           string            `json:"title"`
	VideoId         string            `json:"videoId"`
	Author          string            `json:"author"`
	AuthorId        string            `json:"authorId"`
	AuthorUrl       string            `json:"authorUrl"`
	AuthorVerified  bool              `json:"authorVerified"`
	VideoThumbnails []ThumbnailObject `json:"videoThumbnails"`
	Description     string            `json:"description"`
	DescriptionHtml string            `json:"descriptionHtml"`
	ViewCount       int64             `json:"viewCount"`
	ViewCountText   string            `json:"viewCountText"`
	LengthSeconds   int64             `json:"lengthSeconds"`
	Published       time.Time         `json:"published"`
	PublishedText   string            `json:"publishedText"`
	// Only available on premiered videos
	PremiereTimestamp time.Time `json:"premiereTimestamp"`
	LiveNow           bool      `json:"liveNow"`
	Premium           bool      `json:"premium"`
	IsUpcoming        bool      `json:"isUpcoming"`
	IsNew             bool      `json:"isNew"`
	Is4k              bool      `json:"is4K"`
	Is8k              bool      `json:"is8K"`
	IsVr180           bool      `json:"isVr180"`
	IsVr360           bool      `json:"isVr360"`
	Is3d              bool      `json:"is3D"`
	HasCaptions       bool      `json:"hasCaptions"`
}

type ChannelObject struct {
	Type             string            `json:"type"` // "channel"
	Author           string            `json:"author"`
	AuthorId         string            `json:"authorId"`
	AuthorUrl        string            `json:"authorUrl"`
	AuthorVerified   bool              `json:"authorVerified"`
	AuthorThumbnails []ThumbnailObject `json:"authorThumbnails"`
	AutoGenerated    bool              `json:"autoGenerated"`
	SubCount         int64             `json:"subCount"`
	VideoCount       int64             `json:"videoCount"`
	Description      string            `json:"description"`
	DescriptionHtml  string            `json:"descriptionHtml"`
}

type PlaylistObject struct {
	Type              string `json:"type"` // "playlist"
	Title             string `json:"title"`
	PlaylistId        string `json:"playlistId"`
	PlaylistThumbnail string `json:"playlistThumbnail"`
	Author            string `json:"author"`
	AuthorId          string `json:"authorId"`
	AuthorUrl         string `json:"authorUrl"`
	AuthorVerified    bool   `json:"authorVerified"`
	VideoCount        int64  `json:"videoCount"`
	Videos            []struct {
		Title           string            `json:"title"`
		VideoId         string            `json:"videoId"`
		LengthSeconds   int64             `json:"lengthSeconds"`
		VideoThumbnails []ThumbnailObject `json:"videoThumbnails"`
	} `json:"videos"`
}
