// SPDX-FileCopyrightText: 2025 Antoni Szymański
// SPDX-License-Identifier: MPL-2.0

package invidious

import "time"

func (c *Client) Channel(id string) (*ChannelResponse, error) {
	var resp ChannelResponse
	if err := c.call(&requestConfig{
		Method: "GET",
		Path:   "/api/v1/channels/" + id,
		Output: &resp,
	}); err != nil {
		return nil, err
	}
	return &resp, nil
}

type ChannelResponse struct {
	Author           string          `json:"author"`
	AuthorId         string          `json:"authorId"`
	AuthorUrl        string          `json:"authorUrl"`
	AuthorVerified   bool            `json:"authorVerified"`
	AuthorBanners    []ImageObject   `json:"authorBanners"`
	AuthorThumbnails []ImageObject   `json:"authorThumbnails"`
	SubCount         int64           `json:"subCount"`
	TotalViews       int64           `json:"totalViews"`
	Joined           time.Time       `json:"joined"`
	AutoGenerated    bool            `json:"autoGenerated"`
	IsFamilyFriendly bool            `json:"isFamilyFriendly"`
	Description      string          `json:"description"`
	DescriptionHtml  string          `json:"descriptionHtml"`
	AllowedRegions   []string        `json:"allowedRegions"`
	Tabs             []string        `json:"tabs"`
	LatestVideos     []VideoObject   `json:"latestVideos"`
	RelatedChannels  []ChannelObject `json:"relatedChannels"`
}
